name: "General_Issue"
description: "Can be used for general issues"
title: Unable to Commit code to GitHub
body:
- type: dropdown
  id: download
  attributes:
    label: Select Type of Issue from the dropdown
    options:
      - GitHub Commit
      - Code Debug
      - Unable to access Azure Portal
      - Update details in Attendence list
      - Others
  validations:
    required: true
- type: textarea
  attributes:
    label: "Type your Issue below"
  
