
name: "General_Issue"
description: "Can be used for general issues"
label: ["Bug", "Needs Triage"]
title: Unable to Commit code to GitHub
body:
- type: dropdown
  id: typeofissue
  attributes:
    label: Select Type of Issue from the dropdown
    options:
      - GitHub Commit
      - Code Debug
      - Unable to access Azure Portal
      - Update details in Attendence list
      - Others
  validations:
    required: true
- type: textarea
  attributes:
    label: "Type your Issue below"
- type: checkboxes
  id: selfdeclaration 
  attributes:
    label: Self declarations 
    description: You may select more than one.
    options:
      - label: I had made my self research before raising an issue
        required: true
