name: "General_Issue"
description: "Can be used for general issues"
body:
- type: markdown
  attributes:
    value: "Welcome to General Issue page"
- type: textarea
  attributes:
    label: "Type your Issue below"
