name: "Project review request"
description: "Can be used for your final project submission's"
title: "ML23/24-1 Project_Name Group_Name"
# labels: [""]
assignees: ["ddobric"]
body:
- type: dropdown
  id: typeofenvi
  attributes:
    label: Choose the Github Repository from the dropdown menu.
    options:
      - se-cloud-2023-2024
      - se-cloud-2022-2023
      - Forked NeocortexApi
      - Others
  validations:
    required: true
- type: textarea
  attributes:
    label: "Please enter your issue in the space provided below."
- type: textarea
  attributes:
    label: "Please include corresponding images or screenshots that reference the identified issue."
  validations:
    required: true
- type: textarea
  attributes:
    label: "Please share the URL of the code related to the issue."
- type: checkboxes
  id: selfdeclaration 
  attributes:
    label: Self declarations 
    options:
      - label: I conducted research on my own before bringing up the matter.
        required: true
