name: "Project review request"
description: "Can be used for your final project submission's"
title: "ML23/24-1 Project_Name Group_Name"
labels: ["project-review-request"]
assignees: ["ddobric"]
body:
- type: markdown
  attributes:
    value: "Hello Professor,"
- type: markdown
  attributes:
    value: "We would like you to review our software engineering project. Please find detailed information and accompanying snapshots below for your reference. "
- type: textarea
  attributes:
    label: Provide all team members individual Commit links for the project. For Example Best_Group_Ever?author=Github_UserName
  validations:
    required: true
- type: checkboxes
  id: documentationfolder 
  attributes:
    label: Documentation folder must contain the following files
    options:
      - label: Research paper in word format - Document the project by using of IEEE template. The structure should be followed by IMRAD standard.File Name: Best_Group_Ever-Paper.docx
        required: true
      - label: Research paper in PDF format. (File Name: Best_Group_Ever-Paper.pdf)
        required: true
      - label: Project Power Point Presentation. (File Name: Best_Group_Ever-Project_Presentation.pptx)
        required: true
      - label: Presentation Recorded video
        required: true
      - label: Readme file - The md should include the architecture of the solution (include at least one picture) and instructions to ensure the reader to reproduce what you did in the project.
        required: true
- type: textarea
  attributes:
    label: Provide the URL for the above Documentation folder
  validations:
    required: true
- type: textarea
  attributes:
    label: Brief summary of your project.
  validations:
    required: true
- type: textarea
  attributes:
    label: Provide project repository URL
  validations:
    required: true
- type: textarea
  attributes:
    label: Link of main Project code file
  validations:
    required: true
- type: textarea
  attributes:
    label: Link of Unit tests code file
- type: textarea
  attributes:
    label: "Mention names of the existing program Files, if any changes were made to it"

